services:
  db:
    image: postgres:16-alpine
    container_name: cpf_searcher_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cpf_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: cpf_searcher_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cpf_db
    command: sh -c "uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
